### ISSUE TITLE
Idea: Accept data query param in root or button to edit

### ISSUE THREAD

**Issue by sabatesduran** [sujjeee/linknode#1]
Would be nice if after you made the link you can edit it by adding something to the url or having a button in the app that you can paste the link and populates the data

**Comment by sujjeee** [comment]
you mean like a template?

**Comment by sabatesduran** [comment]
just to be able to edit an old link

**Comment by sabatesduran** [comment]
to be more clear, the same way you add the demo data would be nice to be able to load a link that I've created before to update it

**Comment by sujjeee** [comment]
yeah its kind of a template, but it's too long for users to copy , then paste it into input field and then make changes...
